import type { Food, Nutrients, Serving } from '../types'

/**
 * The bulk offline food database, generated by `scripts/build-food-db.mjs`.
 *
 * It ships as a static JSON file rather than a bundled module so it stays out
 * of the main JS payload — nothing downloads it until the first search, and the
 * browser's HTTP cache handles it from then on.
 *
 * Rows are stored positionally (`v` is a fixed-order nutrient array) because at
 * tens of thousands of records, object keys are most of the file size.
 */

interface PackedFood {
  c: string // barcode
  n: string // name
  b: string // brand
  s: string // serving label
  g: number // serving grams
  v: number[] // nutrients, in NUTRIENT_ORDER
}

interface PackedDb {
  version: number
  count: number
  foods: PackedFood[]
}

const NUTRIENT_ORDER: (keyof Nutrients)[] = [
  'calories', 'carbs', 'fat', 'protein', 'satFat', 'polyFat', 'monoFat',
  'transFat', 'cholesterol', 'sodium', 'potassium', 'fiber', 'sugar',
  'vitaminA', 'vitaminC', 'calcium', 'iron',
]

function unpack(p: PackedFood): Food {
  const nutrients = {} as Nutrients
  NUTRIENT_ORDER.forEach((k, i) => {
    nutrients[k] = p.v[i] ?? 0
  })

  const grams = p.g > 0 ? p.g : 100
  const servings: Serving[] = [{ label: p.s, grams, multiplier: 1 }]
  if (Math.abs(grams - 100) > 0.01) {
    servings.push({ label: '100 g', grams: 100, multiplier: 100 / grams })
  }
  servings.push({ label: '1 g', grams: 1, multiplier: 1 / grams })
  servings.push({ label: '1 oz', grams: 28.35, multiplier: 28.35 / grams })

  return {
    id: `off_${p.c}`,
    name: p.n,
    brand: p.b || undefined,
    nutrients,
    servings,
    source: 'off',
    barcode: p.c,
  }
}

let cache: Food[] | null = null
let inflight: Promise<Food[]> | null = null
let failed = false

/** Loaded once, then held in memory for the session. */
export function loadFoodDb(): Promise<Food[]> {
  if (cache) return Promise.resolve(cache)
  if (failed) return Promise.resolve([])
  if (inflight) return inflight

  inflight = fetch("/food-db.json")
    .then((r) => {
      if (!r.ok) throw new Error(String(r.status))
      return r.json() as Promise<PackedDb>
    })
    .then((db) => {
      cache = db.foods.map(unpack)
      return cache
    })
    .catch(() => {
      // Absent database is not an error — the app still has its seed foods.
      failed = true
      return []
    })
    .finally(() => {
      inflight = null
    })

  return inflight
}

export function foodDbReady(): boolean {
  return cache !== null
}

export function foodDbSize(): number {
  return cache?.length ?? 0
}

/** Kick off the download without waiting, so search feels instant later. */
export function warmFoodDb(): void {
  void loadFoodDb()
}
