import type { Food, Nutrients, Serving } from '../types'

/**
 * The bulk offline food database, generated by `scripts/build-usda-db.mjs`.
 *
 * It ships as static JSON rather than a bundled module so it stays out of the
 * main JS payload. Nothing downloads until the first search, and the browser's
 * HTTP cache handles it from then on.
 *
 * Rows are stored positionally (`v` is a fixed-order nutrient array) because at
 * these counts, object keys are most of the file size.
 *
 * ## Two files
 *
 * `food-db.json` (the core) holds every generic food plus the 45,000
 * highest-ranked branded products, and covers ordinary searching on its own.
 * `food-db-ext.json` holds the long tail of branded products. Three times
 * larger, for the obscure end of the shelf.
 *
 * Both load automatically. The tail is fetched right behind the core rather
 * than waiting to be asked for.
 *
 * ## Rows stay packed
 *
 * Rows are kept in their on-the-wire shape and only turned into `Food` objects
 * when something is actually going to be shown. Eagerly unpacking the core
 * costs about 100 MB of heap to materialise nutrient and serving objects for
 * rows nobody will ever look at; a search displays sixty of them. `searchLocal`
 * scores against the lowercased name and brand arrays below and unpacks only
 * what it returns.
 */

export interface PackedFood {
  c: string // barcode, or `usda<fdcId>` where there is no barcode
  n: string // name
  b: string // brand
  k: 0 | 1 // 0 = generic (USDA reference), 1 = branded
  p: [string, number][] // portions: label, grams
  v: number[] // nutrients per 100 g, in NUTRIENT_ORDER
}

interface PackedDb {
  version: number
  count: number
  foods: PackedFood[]
}

const NUTRIENT_ORDER: (keyof Nutrients)[] = [
  'calories', 'carbs', 'fat', 'protein', 'satFat', 'polyFat', 'monoFat',
  'transFat', 'cholesterol', 'sodium', 'potassium', 'fiber', 'sugar',
  'vitaminA', 'vitaminC', 'calcium', 'iron',
]

/** Nutrients are stored per 100 g; a Food carries them for `servings[0]`. */
export function unpackRow(p: PackedFood): Food {
  const portions = p.p.length ? p.p : ([['100 g', 100]] as [string, number][])
  const baseGrams = portions[0][1] > 0 ? portions[0][1] : 100
  const factor = baseGrams / 100

  const nutrients = {} as Nutrients
  NUTRIENT_ORDER.forEach((k, i) => {
    nutrients[k] = (p.v[i] ?? 0) * factor
  })

  const servings: Serving[] = portions.map(([label, grams]) => ({
    label,
    grams,
    multiplier: grams / baseGrams,
  }))

  // Weight-based portions let anyone log an amount the label doesn't offer.
  const has = (g: number) => servings.some((s) => Math.abs((s.grams ?? -1) - g) < 0.01)
  if (!has(100)) servings.push({ label: '100 g', grams: 100, multiplier: 100 / baseGrams })
  if (!has(1)) servings.push({ label: '1 g', grams: 1, multiplier: 1 / baseGrams })
  if (!has(28.35)) {
    servings.push({ label: '1 oz', grams: 28.35, multiplier: 28.35 / baseGrams })
  }

  const usda = p.c.startsWith('usda')
  return {
    id: usda ? p.c : `off_${p.c}`,
    name: p.n,
    brand: p.b || undefined,
    nutrients,
    servings,
    source: 'usda',
    barcode: usda ? undefined : p.c,
    generic: p.k === 0,
  }
}

/* --------------------------------------------------------- search index -- */

/**
 * Rows plus their lowercased name and brand, held as parallel arrays.
 *
 * Lowercasing inside the scorer would mean a few hundred thousand string
 * allocations per keystroke, which dwarfs the comparison work itself.
 */
export interface FoodIndex {
  rows: PackedFood[]
  namesLc: string[]
  brandsLc: string[]
}

const index: FoodIndex = { rows: [], namesLc: [], brandsLc: [] }

function append(rows: PackedFood[]) {
  for (const r of rows) {
    index.rows.push(r)
    index.namesLc.push(r.n.toLowerCase())
    index.brandsLc.push(r.b ? r.b.toLowerCase() : '')
  }
}

export function foodIndex(): FoodIndex {
  return index
}

/* ------------------------------------------------------------- two-stage -- */

let coreLoaded = false
let extLoaded = false
let coreInflight: Promise<void> | null = null
let extInflight: Promise<void> | null = null
let coreFailed = false

const listeners = new Set<() => void>()

/** Notified when the database grows, so an open search can re-run. */
export function onFoodDbGrown(fn: () => void): () => void {
  listeners.add(fn)
  return () => listeners.delete(fn)
}

function announce() {
  for (const fn of listeners) fn()
}

async function fetchDb(url: string): Promise<PackedFood[]> {
  const res = await fetch(url)
  if (!res.ok) throw new Error(String(res.status))
  const db = (await res.json()) as PackedDb
  return db.foods
}

/** Loaded once, then held in memory for the session. */
export function loadFoodDb(): Promise<void> {
  if (coreLoaded || coreFailed) return Promise.resolve()
  if (coreInflight) return coreInflight

  coreInflight = fetchDb('/food-db.json')
    .then((rows) => {
      append(rows)
      coreLoaded = true
      announce()
      /* The long tail follows automatically. It used to be opt-in behind a
         setting, because it roughly triples the heap, but a food that only
         turns up once you have found and enabled a preference is, for
         practical purposes, missing. Deliberately not awaited: the first
         search must never wait on it. */
      void loadExtendedFoodDb()
    })
    .catch(() => {
      // An absent database is not an error. The app still has its seed foods.
      coreFailed = true
    })
    .finally(() => {
      coreInflight = null
    })

  return coreInflight
}

/** Fetches the long tail. Safe to call repeatedly; only the first does work. */
export function loadExtendedFoodDb(): Promise<void> {
  if (extLoaded) return Promise.resolve()
  if (extInflight) return extInflight

  extInflight = loadFoodDb()
    .then(() => fetchDb('/food-db-ext.json'))
    .then((rows) => {
      append(rows)
      extLoaded = true
      announce()
    })
    .catch(() => {
      // The core database alone is a perfectly usable app.
    })
    .finally(() => {
      extInflight = null
    })

  return extInflight
}

export function foodDbReady(): boolean {
  return coreLoaded
}

export function foodDbSize(): number {
  return index.rows.length
}

export function extendedDbLoaded(): boolean {
  return extLoaded
}

/** Kick off the download without waiting, so search feels instant later. */
export function warmFoodDb(): void {
  void loadFoodDb()
}
